[package]
name = "shan-shui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
debug = true

[dependencies]
base64 = "0.13.0"
resvg = "0.19.0"
tiny-skia = "0.6.1"
usvg = "0.19.0"
svg = "0.10.0"