[package]
name = "shan-shui-native"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shan-shui = { path = "../core" }
resvg = "0.19.0"
tiny-skia = "0.6.1"
usvg = "0.19.0"